cc_library(
    name = "etfpp",
    srcs = [
         "etf.cc",
         # "term.cc",
         "term_entry.cc",
         "utils.cc"
    ],

    hdrs = [
         "etf.h",
         # "term.h",
         "term_entry.h",
         "utils.h"
    ],

    visibility = ["//visibility:public"]
)