name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get crazypants C++20 and bazel
        run: |
          sudo apt install gcc-10 gcc-10-base gcc-10-doc g++-10 libstdc++-10-dev
      - name: actions-bazelisk
        # You may pin to the exact commit or the version.
        # uses: suyash/actions-bazelisk@68a5d2f5c05fb6bc2fdc05d3d8fe9b4f9c864637
        uses: suyash/actions-bazelisk@v1
      - name: Bazel Build and Test
        run: bazel test --test_output=errors ...
